import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // 1. Trouver l'utilisateur
  const user = await prisma.user.findUnique({
    where: { email: 'julien.paulais@vinci-construction.com' }
  })
  if (!user) throw new Error('Utilisateur julien.paulais@vinci-construction.com introuvable')
  console.log(`Utilisateur trouvé : ${user.name} (${user.id})`)

  // 2. Trouver le projet contenant "Mans"
  const projet = await prisma.projet.findFirst({
    where: {
      members: { some: { userId: user.id } },
      name: { contains: 'Mans', mode: 'insensitive' }
    }
  })
  if (!projet) throw new Error('Projet contenant "Mans" introuvable pour cet utilisateur')
  console.log(`Projet trouvé : ${projet.name} (${projet.id})`)

  // 3. Supprimer tous les rapports existants de ce projet
  const deleted = await prisma.rapportJournalier.deleteMany({
    where: { projetId: projet.id }
  })
  console.log(`${deleted.count} rapports existants supprimés`)

  // 4. Créer chaque rapport avec les données EXACTES
  const rapports = [
    {
      titre: 'RJ N°17',
      date: new Date('2026-02-02'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Récupération demi aiguillage et cœur\nBourrage et réglage ADV sauf 114 et 78/80\nPrépa demi aiguillage 114\nPrépa RR\nBourrage des Tba remplacé Voie 0 à 10\nNettoyage',
      commentaire: null,
    },
    {
      titre: 'RJ N°18',
      date: new Date('2026-02-03'),
      posteNuit: true,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Demi aiguillage 114 + Bourrage\nPose du cœur du 118\nRT 2 R6 adv 118\nCoupon V0 4,7m\n2 création de JO V4\nRégalage\nAcheminement 250 Tba P7',
      commentaire: null,
    },
    {
      titre: 'RJ N°19',
      date: new Date('2026-02-04'),
      posteNuit: true,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: '1 coupon 4,63m V0\n1 coupon 4,07 V1\n2 coupon 6m V7\nRéglage des cotes cœur 118 (récupéré)\nRéglage adv et voie 14 à 9\nReprise écartement TJD 530\nAppro 800 Tb A P7',
      commentaire: null,
    },
    {
      titre: 'RJ N°20',
      date: new Date('2026-02-05'),
      posteNuit: true,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Création jo 2 V10 + 1 RT\nCréation jo 2 V12 + 1 RT + 22 conso\nV13 2 création JO + 22 conso\n2 création de JO V14 + 1 RT et 18 conso\nCoupon V9 5m\nFin du régalage\nTentative de reprise écartement TJD 530\nAcheminement de ballast P7',
      commentaire: null,
    },
    {
      titre: 'RJ N°21',
      date: new Date('2026-02-06'),
      posteNuit: true,
      heureDebut: '08:00',
      heureFin: '12:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Coupon V6 4m\nAcheminement du matériel RVB P7\nCréation de JO V14 ×2\nNettoyage',
      commentaire: null,
    },
    {
      titre: 'RJ N°22',
      date: new Date('2026-02-09'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:40',
      heureFinPrevue: '04:30',
      heureRestituee: '04:29',
      production: 'Dépose de 144m de voie pour RVB\nDistribution de traverses et rails\nDétirfonnage et nettoyage de 30 chambrées pour RT V17\nMise en place d\'une traversée des voies 25 à 19 pour appro',
      commentaire: null,
    },
    {
      titre: 'RJ N°23',
      date: new Date('2026-02-10'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:23',
      heureFinPrevue: '04:30',
      heureRestituee: '04:28',
      production: 'Terrassement et sous couche sur 144m pour RVB\nPose de traverses et rails sur 72m pour RVB\nNettoyage de 50 chambrées pour RT en recherche\nMise en place de la traversée des voies V25 à V19',
      commentaire: null,
    },
    {
      titre: 'RJ N°24',
      date: new Date('2026-02-11'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:23',
      heureFinPrevue: '04:30',
      heureRestituee: '04:30',
      production: 'Pose de rail et traverses et raccordement zone RVB\nBallastage sur les 144m du RVB et bourrage',
      commentaire: null,
    },
    {
      titre: 'RJ N°25',
      date: new Date('2026-02-12'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:22',
      heureFinPrevue: '04:30',
      heureRestituee: '03:59',
      production: 'Pose de connexion RR95 et retrait du RCT\nComplément de ballast sur 144m de RVB\nAppro de Tba pour RT V19',
      commentaire: null,
    },
    {
      titre: 'RJ N°26',
      date: new Date('2026-02-16'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:14',
      heureFinPrevue: '04:30',
      heureRestituee: '04:14',
      production: 'RT 50 Tba V19\nAppro des TB V11\nCréation cheminement provisoire V25 à 11',
      commentaire: null,
    },
    {
      titre: 'RJ N°27',
      date: new Date('2026-02-17'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '23:15',
      heureFinPrevue: '04:30',
      heureRestituee: '04:15',
      production: 'RT V19 de 111 traverses\nBallastage des 50 Tb de la nuit précédente\nV19 dégarnissage de 130 Tb',
      commentaire: null,
    },
    {
      titre: 'RJ N°28',
      date: new Date('2026-02-18'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:50',
      heureFinPrevue: '04:30',
      heureRestituee: '04:19',
      production: 'RT de 103 Tb V19\nBallastage et nettoyage de 50 Tb\nDégarnissage de 50 Tb\nCréation d\'une traversée jusqu\'à V11\nDistribution de traverses pour V5',
      commentaire: null,
    },
    {
      titre: 'RJ N°29',
      date: new Date('2026-02-19'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:28',
      heureFinPrevue: '04:30',
      heureRestituee: '04:15',
      production: 'RT de 56 Tb V19\nBallastage et nettoyage V19',
      commentaire: 'Pelle en panne V19',
    },
    {
      titre: 'RJ N°30',
      date: new Date('2026-02-23'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '23:32',
      heureFinPrevue: '04:15',
      heureRestituee: '04:14',
      production: 'Ballastage V19\nRT 61 Tba V5\nNettoyage',
      commentaire: null,
    },
    {
      titre: 'RJ N°31',
      date: new Date('2026-02-24'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '23:00',
      heureFinPrevue: '04:15',
      heureRestituee: '04:15',
      production: 'RT 63 Tba V5',
      commentaire: null,
    },
    {
      titre: 'RJ N°32',
      date: new Date('2026-02-25'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:45',
      heureFinPrevue: '04:15',
      heureRestituee: '04:14',
      production: 'RT V5 70 Tba',
      commentaire: 'V13 arraché à côté du passe engin et relevé de 45mm à reprendre sur 20m',
    },
    {
      titre: 'RJ N°33',
      date: new Date('2026-02-26'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:41',
      heureFinPrevue: '04:15',
      heureRestituee: '04:13',
      production: 'RT V5 13 Tba\nNettoyage et distribution matériel',
      commentaire: 'Flexible de pelle rompu et réparation de 1h30 à 4h10 V7',
    },
    {
      titre: 'RJ N°34',
      date: new Date('2026-03-02'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '23:40',
      heureFinPrevue: '04:30',
      heureRestituee: '04:18',
      production: 'V9 RT 48 Tba 2 Tb Ballastage et bourrage\nV19 nettoyage',
      commentaire: null,
    },
    {
      titre: 'RJ N°34 bis',
      date: new Date('2026-03-02'),
      posteNuit: false,
      heureDebut: '09:50',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Remplacement des demi-aiguillages du Brt 78\nPanne pelle RR : remplacement de flexible\nChargement TBA dans camion par pelle RR',
      commentaire: null,
    },
    {
      titre: 'RJ N°35',
      date: new Date('2026-03-03'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '23:12',
      heureFinPrevue: '04:30',
      heureRestituee: '04:26',
      production: 'V9 RT de 64 Tba\nNettoyage et évacuation entre V7 et V9\nNettoyage V19',
      commentaire: null,
    },
    {
      titre: 'RJ N°35 bis',
      date: new Date('2026-03-03'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Réglage et serrage des demi-aiguillages du Brt 78\nPanne pelle rail-route\nChargement des TBA dans camion par pelle RR',
      commentaire: null,
    },
    {
      titre: 'RJ N°36',
      date: new Date('2026-03-04'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:00',
      heureDebutPrevue: '22:48',
      heureFinPrevue: '04:30',
      heureRestituee: '04:33',
      production: 'V19 ballastage + bourrage\nV13 abaissement de la voie + 15 Tba changées + bourrage',
      commentaire: null,
    },
    {
      titre: 'RJ N°36 bis',
      date: new Date('2026-03-04'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'RT 8 TBA\nRéparation de la pelle\nChargement des TBA dans camion par pelle RR\nagenT LAM absent : remplacé par agent SNCF\n1 RR',
      commentaire: null,
    },
    {
      titre: 'RJ N°37',
      date: new Date('2026-03-05'),
      posteNuit: true,
      heureDebut: '20:30',
      heureFin: '05:46',
      heureDebutPrevue: '22:58',
      heureFinPrevue: '04:30',
      heureRestituee: '05:31',
      production: 'Nettoyage V19 et V9\nComplément de ballast V19 et V13\nBalayage V19 et V9\nPassage du compacteur dans les pistes\nRetrait du passage de V25 à V11',
      commentaire: null,
    },
    {
      titre: 'RJ N°37 bis',
      date: new Date('2026-03-05'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Passage chariot AMBERT dans 7 ADV\nRemplacement éclisses fissurées et boulons cassés\nPas de pelle',
      commentaire: null,
    },
    {
      titre: 'RJ N°38',
      date: new Date('2026-03-06'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '12:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Passage chariot AMBERT dans 3 ADV\nConso voie 5 du passe-pied à la base vie',
      commentaire: null,
    },
    {
      titre: 'RJ N°39',
      date: new Date('2026-03-09'),
      posteNuit: false,
      heureDebut: '09:50',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'RR voie 4 (4 ml)\nInjection TB pour JO (2 TB)',
      commentaire: null,
    },
    {
      titre: 'RJ N°40',
      date: new Date('2026-03-10'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Finitions base arrière',
      commentaire: null,
    },
    {
      titre: 'RJ N°41',
      date: new Date('2026-03-11'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Finitions base arrière',
      commentaire: null,
    },
    {
      titre: 'RJ N°41 bis',
      date: new Date('2026-03-11'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '16:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Finitions travaux Poste 7 Le Mans\nFinitions Voies 11 à 25',
      commentaire: null,
    },
    {
      titre: 'RJ N°42',
      date: new Date('2026-03-12'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Finitions base arrière',
      commentaire: null,
    },
    {
      titre: 'RJ N°42 bis',
      date: new Date('2026-03-12'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '16:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Finitions travaux Poste 7 Le Mans\nFinitions Voies 11 à 25',
      commentaire: 'Panne pelle RR : agent LAM utilisé à 50%',
    },
    {
      titre: 'RJ N°43',
      date: new Date('2026-03-13'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '12:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Finitions base arrière',
      commentaire: 'Pas d\'agent LAM aujourd\'hui',
    },
    {
      titre: 'RJ N°43 bis',
      date: new Date('2026-03-13'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '12:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Finitions travaux Poste 7 Le Mans\nFinitions Voies 11 à 25',
      commentaire: 'Agent LAM absent : remplacé quelques heures par agent SNCF',
    },
    {
      titre: 'RJ N°44',
      date: new Date('2026-03-16'),
      posteNuit: false,
      heureDebut: '09:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Serrage conso Voies 0 à 16',
      commentaire: 'Matériel prêté à l\'entreprise : 2 paquets de 500 chevilles bois, 1 boite de 500 Vortoks',
    },
    {
      titre: 'RJ N°45',
      date: new Date('2026-03-17'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Serrage conso Voies 0 à 16',
      commentaire: 'Panne pelle RR : agent LAM utilisé à 50%',
    },
    {
      titre: 'RJ N°46',
      date: new Date('2026-03-18'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Serrage conso Voies 0 à 16',
      commentaire: 'Agent LAM absent : remplacé quelques heures par agent SNCF',
    },
    {
      titre: 'RJ N°47',
      date: new Date('2026-03-19'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '17:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Serrage conso Voies 0 à 16',
      commentaire: null,
    },
    {
      titre: 'RJ N°48',
      date: new Date('2026-03-20'),
      posteNuit: false,
      heureDebut: '08:00',
      heureFin: '12:00',
      heureDebutPrevue: null,
      heureFinPrevue: null,
      heureRestituee: null,
      production: 'Serrage conso Voies 0 à 16',
      commentaire: null,
    },
  ]

  console.log(`\nCréation de ${rapports.length} rapports...`)

  let created = 0
  for (const rj of rapports) {
    await prisma.rapportJournalier.create({
      data: {
        projetId: projet.id,
        date: rj.date,
        nomChantier: 'Connexe BA Le Mans',
        titre: rj.titre,
        posteNuit: rj.posteNuit,
        heureDebut: rj.heureDebut,
        heureFin: rj.heureFin,
        heureDebutPrevue: rj.heureDebutPrevue,
        heureFinPrevue: rj.heureFinPrevue,
        heureRestituee: rj.heureRestituee,
        production: rj.production,
        commentaire: rj.commentaire,
        travaux: [],
        redacteurId: user.id,
        valide: true,
      }
    })
    created++
    console.log(`  ${rj.titre} - ${rj.date.toISOString().slice(0, 10)} - ${rj.posteNuit ? 'NUIT' : 'JOUR'} ${rj.heureDebut}-${rj.heureFin}`)
  }

  console.log(`\n${created} rapports journaliers créés pour le projet "${projet.name}"`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
